Repository AjouParam/Dandelion, pull requests merged in 2021-11, with the labels that each got.

#85 쪽지 스타일 작업
  client/package-lock.json
  client/package.json
  client/src/assets/index.js
  client/src/assets/mindle/backup/level_1.png
  client/src/assets/mindle/backup/level_2.png
  client/src/assets/mindle/backup/level_3.png
  client/src/assets/mindle/backup/level_4.png
  client/src/assets/mindle/level_1.png
  client/src/assets/mindle/level_2.png
  client/src/assets/mindle/level_3.png
  client/src/assets/mindle/level_4.png
  client/src/assets/tester/tester1.png
  client/src/assets/tester/tester2.png
  client/src/assets/tester/tester3.png
  client/src/assets/tester/tester4.png
  client/src/assets/tester/tester5.png
  client/src/components/ImageButton.js
  client/src/components/MailImage.js
  client/src/components/index.js
  client/src/components/post/Mail.js
  client/src/controller/mapCtrl.js
  client/src/controller/postCtrl.js
  client/src/navigations/MainStack.js
  client/src/screens/Login.js
  client/src/screens/Maps.js
  client/src/screens/PostContainer.js
  client/src/screens/myPage/channel.js
  client/src/screens/myPage/mail.js
  client/src/screens/myPage/mail_dummy.json
  client/src/screens/myPage/post.js
  client/yarn.lock
Labels: front-end, ✨feature, 🌹Style, 🌼design

#84 Feat f comments
  client/.gitignore
  client/package.json
  client/src/components/CustomHeader.js
  client/src/components/MapsRenderHeader.js
  client/src/components/MindlePostContent.js
  client/src/components/post/Mindle.js
  client/src/components/post/Post.js
  client/src/components/post/comment.js
  client/src/components/post/commentInput.js
  client/src/contexts/commentState.js
  client/src/controller/MindleInfoCtrl.js
  client/src/screens/Maps.js
  client/src/screens/MindlePost.js
  client/src/screens/detailPage/mindle.js
  client/src/screens/detailPage/post.js
  client/src/screens/index.js
  client/src/screens/mindlePage/MakePost.js
  client/src/screens/mindlePage/MindleInfo.js
  client/src/screens/mindlePage/MindlePost.js
  client/src/screens/mindlePage/MindlePreview.js
  client/src/screens/mindlePage/MindleSelect.js
  client/src/screens/myPage/mindle.js
  client/src/utils/utilConstant.js
Labels: front-end, ✨feature, 🛠refactoring, 🌹Style

#87 Style : 민들레 게시글 디자인 적용
  client/src/assets/Button/back_button.svg
  client/src/assets/index.js
  client/src/assets/post/back_button.png
  client/src/assets/post/back_button.svg
  client/src/assets/post/comment.png
  client/src/assets/post/comment.svg
  client/src/assets/post/like_clicked.png
  client/src/assets/post/like_unclicked.png
  client/src/assets/post/like_unclicked.svg
  client/src/assets/post/post_add.png
  client/src/assets/post/post_add.svg
  client/src/assets/post/post_delete.png
  client/src/assets/post/post_delete.svg
  client/src/assets/post/post_menu.png
  client/src/assets/post/post_menu.svg
  client/src/assets/post/post_menu_edit.png
  client/src/assets/post/post_menu_edit.svg
  client/src/assets/post/svgtopng.zip
  client/src/assets/profile/profile_default.png
  client/src/assets/profile/profile_default.svg
  client/src/components/MindlePostContent.js
  client/src/screens/Mypage.js
  client/src/screens/mindlePage/MindleInfo.js
  client/src/screens/mindlePage/MindlePost.js
Labels: front-end, 🌹Style

#86 댓글 밑 답글 기능 추가
  client/src/components/CreateMindle.js
  client/src/components/post/CreateSubComments.js
  client/src/components/post/comment.js
  client/src/components/post/subcomment.js
  client/src/controller/dandelionCtrl.js
  client/src/controller/postCtrl.js
  client/src/screens/Maps.js
  client/src/screens/channel.js
  client/src/screens/mindlePage/MindlePost.js
  client/src/screens/myPage/Event.js
  client/src/screens/myPage/channel.js
  client/src/utils/common.js
Labels: front-end, ✨feature, 🌹Style

#91 Feat f hotspot
  client/src/components/post/Mindle.js
  client/src/controller/hotSpotCtrl.js
  client/src/screens/HotSpot.js
  client/src/screens/myPage/globalmindle.js
  client/src/screens/myPage/localmindle.js
  client/yarn.lock
Labels: front-end, ✨feature
